travis:
  secure:
    BINSTAR_TOKEN: LIGNNwNMRHJXN1/NJ2roxvGf3OrNmlb7Vp72QzCgk21EzwC+sRyaMs4THFzXE/bQPvHLF4sTRJeyNTH3vEHsCz124AuwqYzh6N16jt4Yk6lMUJ1gX4+6MzxBv+HSfasHo96aI9RVbYI+bYoNJ017XUtHKcYWD3Kv800F5WPf53VVBq8eW6fM5OSzjTOoMuNSNungareGDf1oEg3MJCT6MxCrDiyKdhtP2P+8k/TtKKbf3n1KCqD0/q1LdGxLzlGB93JXpbELisXYkzvHwql3X1SfUqf+BjR5FtO4eutP55cX6b5vKGACjb3fRHVBD3c5ItdrPn66Y2ArFPuLboR/YKTY1Ams1UlZhjIj/7VgQek0C7quCGmRA5CH7kICjLDsAIjeNUaogEsBwh3N82azmvy19e7Jl1cHI2UiUd64KjJltNnk3WIZpKH29g1dVpSoKAPtqFofyWNyoKCzLCEPywCAx2mBmCtosw4azb1/ii3ZBTr544nsJ7MtMBVEF+8uYMqBYyxAaM9yCyGFGAytrZ91aa3/DFjdvtYy8Rmhwz1nq9QBE+t2kJepfTay8SDYd+7C2u6PkbMAj/axNJGuxfAnIjakK2l+GYtYIi2SEdORckC2dl6XQ44wjIVGVWUjCmjNz0lasdH96gzWo1boawEEJkqmrjZVeCZnxTSzfmw=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
